OPGOPS-2762 Add inspec test to makefile with cleanup.

diff --git a/opg-wordpress-1604/Makefile b/opg-wordpress-1604/Makefile
--- a/opg-wordpress-1604/Makefile
+++ b/opg-wordpress-1604/Makefile
@@ -1,9 +1,22 @@
 .PHONY: build
+SHELL = '/bin/bash'
 
+mkfile_path := $(abspath $(lastword $(MAKEFILE_LIST)))
+current_dir := $(notdir $(patsubst %/,%,$(dir $(mkfile_path))))
+image := $(current_dir)
 registryUrl ?= registry.service.opg.digital
-image = opg-wordpress-1604
+SEED := $(shell /bin/bash -c "echo $$RANDOM")
 
 build:
-        docker build $(no-cache) -t "$(registryUrl)/$(image)" .
-        # docker tag -f "$(registryUrl)/$(image)" "$(registryUrl)/$(image):$(newtag)"
+	echo "Seed: ${SEED}"
+	docker-compose -f tests/docker-compose.yml build
 
+test:
+	echo "Seed: ${SEED}"
+	docker-compose -p "${SEED}" -f tests/docker-compose.yml up -d
+	# Run test, and ensure we cleanup on error
+	inspec exec tests -t docker://${SEED}_basegen_1  ; if [ $$? -ne 0 ] ; then docker-compose -p "${SEED}" -f tests/docker-compose.yml down; exit 1; fi
+	docker-compose -p "${SEED}" -f tests/docker-compose.yml down
+
+clean:
+	docker-compose -p "${SEED}" -f tests/docker-compose.yml down
